@startuml
start
:Model#setPerson(target, editedPerson);

:Check whether target and editedPerson are Trainer;
if () then ([yes])
  :Update trainer in AddressBook;

  :Check whether phone or name changed;
  if () then ([yes])
    :Find all Clients whose
    trainerPhone == originalTrainerPhone;
    :Replace each Client with
    client.withTrainer(newPhone, newName);
  else ([no])
  endif

  :Check whether edited trainer was selected;
  if () then ([yes])
    :Update selectedTrainerPhone;
    :Refresh client predicate;
  else ([no])
  endif
else ([no])
  :Update person normally;
endif
stop
@enduml
